EUREKA_SCHEDULED_SERVICE_ON: 1

app:
  - server: dev
    app: eureka
    uri: https://registryservicedev.app.paas.whereq.com/
  - server: release
    app: eureka
    uri: https://registryservicerelease.app.paas.whereq.com/

whereq:
  reactive:
    h2-console-port: 9080
    eureka:
      service:
        schedule:
          fixedDelay: 60000

    applicationInstanceList:
      - server: dev
        app: eureka
        uri: https://registryservicedev.app.whereq.com/
      - server: release
        app: eureka
        uri: https://registryservicerelease.app.whereq.com/
      - server: stage
        app: eureka
        uri: https://registryservicestage.app.whereq.com/
      - server: production
        app: eureka
        uri: https://registryserviceproduction.app.whereq.com/

logging.level.io.r2dbc.h2: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  r2dbc:
    url: r2dbc:h2:mem:///whereq-reactive
    username: whereq
    password: reactive

  profiles:
    active: dojo_development
    
  application:
    name: whereq-reactive

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
    defaultPropertyInclusion: non-absent
    visibility.field: any
  
  security:
    user:
      name: ${USR:user}
      password: ${PWD:pwd}
  
  servlet:
    multipart.max-file-size: 10MB
    multipart.max-request-size: 10MB
  
  ldap:
    urls: ldap://directory.whereq.com:389
    base: ou=people,o=whereq,c=US
---
spring:
    profiles: dojo_development
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE   
        
